### ISSUE TITLE
Decide the collection channel of data

### ISSUE THREAD

**Issue by kjuk02** [kookmin-sw/2019-cap1-2019_8#1]
Document malicious/benign data is needed to analyze malicious files using machine learning

The document files we're using are HWP, PDF, DOCS, etc

We don't have collection channel of HWP file. So, It is hard to obtain malicious hwp.

**Comment by Leo-Mun** [comment]
https://zeltser.com/malicious-ip-blocklists/

**Comment by Leo-Mun** [comment]
@LightAllWorld 
You have to write a script to crawl the doc/docx files in virusign.com until march 23

**Comment by LightAllWorld** [comment]
Yesterday I wrote a script to crawl doc / docx files from virusign.com, and started crawling target files.

**Comment by LightAllWorld** [comment]
I collected 32 docx files in hybrid-analysis.

**Comment by LightAllWorld** [comment]
Collected 7380 doc files from virusign.

**Comment by kjuk02** [comment]
crawling a doc file named a-z, A-Z in google

**Comment by LightAllWorld** [comment]
Collected almost 8000 doc pdf files from virusign.

**Comment by kjuk02** [comment]
Collected almost 30000 doc files from google, will continue to collect them

**Comment by kjuk02** [comment]
crawling a doc file named redundant permutation of a-z in google

**Comment by LightAllWorld** [comment]
I asked to ViruSign. Because, When I was used the ViruSign, I saw "About 75,778 results (Limited to 10,000)".
I think that I can collect more malicious PDF files from ViruSign.

**Comment by kjuk02** [comment]
Collected almost 13000 doc files from google

**Comment by LightAllWorld** [comment]
I received answer from Virusign. If I want more data to download, I will use query. So, I will study how to use query in Virusign.

**Comment by kjuk02** [comment]
Collected almost 12000 pdf, 1500 docx files from google

**Comment by LightAllWorld** [comment]
Collected 255 doc files from https://app.any.run site.
