### ISSUE TITLE
Feature selection in PDF

### ISSUE THREAD

**Issue by kjuk02** [kookmin-sw/2019-cap1-2019_8#2]

**Comment by LightAllWorld** [comment]
PDF is made up 4 sections. 

1. Header :  This defines the version of PDF specification.
2. Body : This contains the actual content that will be displayed.
3. Cross-reference table : This is a table for PDF viewers to quickly access different objects.
4. Trailer : This defines other meta info of a PDF file.

**Comment by hyeri0903** [comment]
pdfid.py parser can extract 23 features

version, obj, endobj, stream, endstrea, sref, trailer, startxref,
/Page, /Encrypt, ObjStm, /JS, /JavaScript, /AA, /OpenAction,
/AcroForm, /JbIG2Decode, /RichMedia, /Launch, /EmbeddedFile,
/XFA, /URI, /Colors > 2^24

**Comment by LightAllWorld** [comment]
I have found several tools for extracting javascript and structure information from pdf.

1. pdf-parser (https://blog.didierstevens.com/programs/pdf-tools/)
2. pypdf2 (https://github.com/mstamy2/PyPDF2)
3. peepdf (https://eternal-todo.com/tools/peepdf-pdf-analysis-tool)

pypdf2, and peepdf were written in python2. So, I think I chose one method and convert python3.

**Comment by hyeri0903** [comment]
Number of features obtained by modifying pdfid.py : 45

**Used Features:**
version, size, obj, endobj, stream, endstream, xref, trailer, startxref,
/Page, /Encrypt, /ObjStm, /JS, /JavaScript, /AA, /OpenAction, /AcroForm, /JBIG2Decode, /RichMedia, /Launch, /EmbeddedFIle, /XFA, /Colors > 2^24, /Type, /Catalog, /Version, /Pages, /OpenAction, /rovers, /abdula, /Kids, /Count, /S, /Filter, /FlateDecode, /Length, /ASCIIHexDecode, /ASCII85Decode, /LZWDecode, /RunLengthDecode, /CCITTFaxDecode, /JBIG2Decode, /DCTDecode, /JPXDecode, /Crypt

**Comment by LightAllWorld** [comment]
I think we don't have to use JavaScript in PDF. Because if we want to use it, we have to spend more time extracting features. But our service requires less time. Therefore, we do not need to use JavaScript to create feature vectors.

**Comment by hyeri0903** [comment]
pdf-parser.py parser can extract **43 features**

Used Features:
-'Version', 'obj', 'endobj', 'stream', 'endstream', 'xref', 'trailer',
'startxref', '/Page', '/Encrypt', '/ObjStm', '/JS', '/JavaScript',
'/AA', '/OpenAction', '/AcroForm', '/JBIG2Decode', '/RichMedia',
'/Launch', '/EmbeddedFile', '/XFA', '/URI', '/Colors', 'Size',
'/Catalog', '/ExtGState', '/Font', '/FontDescriptor', '/Metadata',
'/OCG', '/OCMD', '/Outlines', '/Pages', '/XRef', '/Annot', '/Filespec',
'/Encoding', '/XObject', '/StructTreeRoot', '/Sig', '/Action', '/3D'

**Comment by LightAllWorld** [comment]
[Result]

- We only use structural features in PDF file.

- Conversion to python 3 takes too much time and effort.

- I found some modules to extracting JavaScript from PDF. But modules are unsuitable for our project.
 1) peepdf is written by python 2, and this module converts the full tag information of the PDF into objects. However, they have a shorter project development period and are difficult to complete within that time.
 2) pdfid is extracting structural features. But, it can not extracting JavaScript in PDF. So, this module can't use for extracting JavaScript from PDF.
 3) pdf-parser is extracting structural JavaScript. It doesn't extract the JavaScript code. Therefore, we can not use this module to extract JavaScript from the PDF.

**Comment by LightAllWorld** [comment]
I think the combination of document frequency and PDF tag information will be a good feature for us.

**Comment by Leo-Mun** [comment]
We have tried to find the df of the tag type with 1000 malicious PDFs and 1000 normal files.

- Types of tags appearing in malicious PDFs : 14351
- Types of tags appearing in normal PDFs : 62369
- intersection of malicious PDFs with normal PDFs : 2393

Tags that appear frequently in malicious PDFs are different from those that appear frequently in normal PDFs

**Therefore, the feature vector of malicious PDF and the feature vector of normal PDF will have different characteristics**

**Comment by Leo-Mun** [comment]
## Top 20 malicious PDF tags df

- /URI 109538
- obj 69489
- endobj 69489
- /Type 67407
- /www 59728
- /A 58837
- /Subtype 58805
- /S 58131
- /Contents 58049
- /M 54910
- /I 54908
- /F 54877
- /H 54873
- /P 54858
- /Rect 54772
- /Link 54769
- /Annot 54768
- /Border 54766
- /NM 54765
- /rdf 23756

## Top 20 normal PDF tags df

- obj 129262
- endobj 129251
- /Type 64510
- /Length 48806
- stream 48729
- endstream 48373
- /Filter 44693
- /FlateDecode 39834
- /Subtype 34163
- /xmpG 30263
- /S 29609
- /Font 20767
- /XObject 17501
- /P 17202
- /rdf 17192
- /K 15577
- /Resources 15065
- /ColorSpace 14473
- /Parent 13896
- /A 13596
