### ISSUE TITLE
Compare Machine Learning algorithms

### ISSUE THREAD

**Issue by kjuk02** [kookmin-sw/2019-cap1-2019_8#3]
Machine learning techniques are diverse and we must find a suitable technique for malicious document detection

**Comment by hyeri0903** [comment]
Malicious Docx (363 files)
Benign Docx (363 files) 
Num of Total Feature : 1285

Compare Machine Learning : LogisticRegression, DecisionTreeClassifier, SVM, GaussianNB, KNeighborsClassifier, RandomForestClassifier, GradientBoostingClassifier
![image](https://user-images.githubusercontent.com/26623530/55550981-a9213900-5714-11e9-8213-2d6c577363d9.png)
